export const types= {
  SIGN_UP : 'USER_SIGN_UP ',
  LOGIN : 'USER_LOGIN ',
  LOGOUT : 'LOGOUT',
 
  ADD_USER_DETAILS_START:'ADD_USER_DETAILS_START',
  ADD_USER_DETAILS_FAILED:'ADD_USER_DETAILS_FAILED',
  ADD_USER_DETAILS_SUCCESS:'ADD_USER_DETAILS_SUCCESS',

  GET_ALL_CONTACTS_START:'GET_ALL_CONTACTS_START',
  GET_ALL_CONTACTS_SUCCESS:'GET_ALL_CONTACTS',
  GET_ALL_CONTACTS_FAILED:'GET_ALL_CONTACTS_FAILED',

  GET_USER_DETAILS_START:'GET_USER_DETAILS_START',
  GET_USER_DETAILS_FAILED:'GET_USER_DETAILS_FAILED',
  GET_USER_DETAILS_SUCCESS:'GET_USER_DETAILS_SUCCESS',

  UPDATE_USER_DETAILS_START:'UPDATE_USER_DETAILS_START',
  UPDATE_USER_DETAILS_FAILED:'UPDATE_USER_DETAILS_FAILED',
  UPDATE_USER_DETAILS_SUCCESS:'UPDATE_USER_DETAILS_SUCCESS',

  HANDLE_FAVOURITE:'HANDLE_FAVOURITE',

  SHOW_TOAST:'SHOW_TOAST',
  HIDE_TOAST:'HIDE_TOAST',

  SET_HOW:'SET_HOW',
  SET_WHO:'SET_WHO',
  SET_WHERE:'SET_WHERE',
  SENT_PUSH_NOTIFICATION:'SENT_PUSH_NOTIFICATION'

}