export const types= {
USER_SIGN_UP : 'USER_SIGN_UP ',
  USER_LOGIN : 'USER_LOGIN ',
  LOGOUT : 'LOGOUT',

 ADD_USER_DETAILS_START:'ADD_USER_DETAILS_START',
  ADD_USER_DETAILS_FAILED:'ADD_USER_DETAILS_FAILED',
  ADD_USER_DETAILS_SUCCESS:'ADD_USER_DETAILS_SUCCESS',

 GET_USER_DETAILS_START:'GET_USER_DETAILS_START',
  GET_USER_DETAILS_FAILED:'GET_USER_DETAILS_FAILED',
  GET_USER_DETAILS_SUCCESS:'GET_USER_DETAILS_SUCCESS',

 UPDATE_USER_DETAILS_START:'UPDATE_USER_DETAILS_START',
  UPDATE_USER_DETAILS_FAILED:'UPDATE_USER_DETAILS_FAILED',
  UPDATE_USER_DETAILS_SUCCESS:'UPDATE_USER_DETAILS_SUCCESS',
}